SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{92ABFEAE34F8B234}PrefabsEditable/Props/Tornado/Tornado_E.et"
  "{15D9B0131FDFA5A4}PrefabsEditable/Props/Wrecks/ZSU_wreck_E.et"
  "{0390F19727D9CC4F}PrefabsEditable/Props/Naval/Grachonok_Boat_E.et"
 }
}